### ISSUE TITLE
Create image gallery for each camp

### ISSUE THREAD

**Issue by InfiniteCoop** [InfiniteCoop/refugee-camps#4]

**Comment by ClareFarley** [comment]
So I figured out the source of the problem. Because the iframe is set to 100%, it makes the iframe height 273.375px. The image is currently set at 284.8px. That is why it is cutting off the bottom of the image. Story Map journal does not allow you to set the height to 100%. I think the best work around will making the image smaller to fit the 273.375px. If you have any other ideas of solutions, let me know.
